#!/bin/bash
# Example script for setting up scheduled tasks

echo "RSS to Kindle Scheduled Push Setup"
echo "==================================="
echo ""
echo "Below are some example cron jobs. Add them with: crontab -e"
echo ""
echo "# Push every day at 7 AM"
echo "0 7 * * * cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "# Push twice a day at 7 AM and 7 PM"
echo "0 7,19 * * * cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "# Push every Monday, Wednesday, and Friday at 8 AM"
echo "0 8 * * 1,3,5 cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "# Push every Sunday at 9 PM (weekly digest)"
echo "0 21 * * 0 cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "Setup steps:"
echo "1. Run 'crontab -e' to edit scheduled tasks"
echo "2. Copy one of the job lines above (adjust the time as needed)"
echo "3. Save and exit"
echo "4. Run 'crontab -l' to verify the task has been added"
echo ""
echo "Notes:"
echo "- Make sure email_config.yaml is correctly configured"
echo "- Make sure the Python path is correct (check with: which python3)"
echo "- Logs will be saved to cron_log.txt"
